template:
  path: enricher.yaml.j2
  type: file

parameters:
  ProjectName: !stack_attr project_code
  S3Url: !environment_variable S3_URL
  OMDBKey: !environment_variable OMDB_API_KEY
  ArtifactBucketName: !environment_variable ARTIFACT_BUCKET_NAME

sceptre_user_data:
  stack_parameters: !stack_attr parameters

hooks:
  after_create:
    - !cmd python ../scripts/pack_and_upload.py --source-file ../src/filter.py --object-key "filter_lambda.zip"
    - !cmd python ../scripts/pack_and_upload.py --source-file ../src/enrich.py --object-key "enrich_lambda.zip"
  after_update:
    - !cmd python ../scripts/pack_and_upload.py --source-file ../src/filter.py --object-key "filter_lambda.zip"
    - !cmd python ../scripts/pack_and_upload.py --source-file ../src/enrich.py --object-key "enrich_lambda.zip"